language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"
  - VERSION="7.0" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo pip install num2words xlrd
  - wget http://sourceforge.net/projects/wkhtmltopdf/files/0.12.2.1/wkhtmltox-0.12.2.1_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2.1_linux-precise-amd64.deb
  - bzr branch lp:~noviat/openobject-addons/extra-7.0 ${HOME}/noviat
  - bzr branch lp:~rcarnes/openerp-shared/7.0 ${HOME}/shared
  - pushd ${HOME}/shared; bzr merge lp:~savoirfairelinux-openerp/openerp-shared/7.0; popd  # TEMP
  - bzr branch lp:~savoirfairelinux-openerp/openerp-usa/npg_bank_account_reconciliation-add_unclear_entries_summation ${HOME}/usa
  - git clone --depth=1 https://github.com/OCA/account-fiscal-rule.git ${HOME}/fiscal-rule -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-financial-reporting.git ${HOME}/finacial-reporting -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-financial-tools.git ${HOME}/financial-tools -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-invoicing.git ${HOME}/account-invoicing -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-payment.git ${HOME}/account-payment -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/bank-statement-reconcile.git ${HOME}/bank-statement-reconcile -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/webkit-tools.git ${HOME}/webkit-tools -b ${VERSION}

script:
  - travis_run_tests

after_success:
  coveralls
