addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

env:
  global:
  - VERSION="7.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: oGR/dBwtppmz8AWPy/1gChKk3TbMOnzHnVxp1ywimKBt7tOtpA8EEgOEY3Zs9xgCa/DYo/Vf5tVtpFw3T9E8ohkqdwr3514dh5zFAASvlkTq7IY623Yntky0Sj4h1edooPFjzm33TzIMB6Vbwv/aZaeJFspV+OWbPPUq7Rel2qI=

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - TESTS="1.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
# Temporarily using transifex branch until merge of https://github.com/OCA/maintainer-quality-tools/pull/186
#  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone --depth=1 https://github.com/Ehtaga/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo pip install num2words xlrd
  - sudo apt-get install xfonts-75dpi
  - wget http://sourceforge.net/projects/wkhtmltopdf/files/archive/0.12.2/wkhtmltox-0.12.2_linux-precise-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.2_linux-precise-amd64.deb
  - bzr branch lp:~noviat/openobject-addons/extra-7.0 ${HOME}/noviat
  - bzr branch lp:~rcarnes/openerp-shared/7.0 ${HOME}/shared
  - pushd ${HOME}/shared; bzr merge lp:~savoirfairelinux-openerp/openerp-shared/7.0; popd  # TEMP
  - bzr branch lp:~savoirfairelinux-openerp/openerp-usa/npg_bank_account_reconciliation-add_unclear_entries_summation ${HOME}/usa
  - git clone --depth=1 https://github.com/OCA/account-fiscal-rule.git ${HOME}/fiscal-rule -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-financial-reporting.git ${HOME}/finacial-reporting -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-financial-tools.git ${HOME}/financial-tools -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-invoicing.git ${HOME}/account-invoicing -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/account-payment.git ${HOME}/account-payment -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/bank-statement-reconcile.git ${HOME}/bank-statement-reconcile -b ${VERSION}
  - git clone --depth=1 https://github.com/OCA/webkit-tools.git ${HOME}/webkit-tools -b ${VERSION}

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
